### ISSUE TITLE
Traceback error on netbox 2.10.1

### ISSUE THREAD

**Issue by tonkatsuki** [lopes/netbox-scanner#27]
Getting this on a brand new install of both netbox and netbox-scanner. Is 2.10.1 supported?

root@HOST netbox-scanner]# python3 netbox-scanner.py nmap
Traceback (most recent call last):
  File "netbox-scanner.py", line 62, in <module>
    format='%(asctime)s\tnetbox-scanner\t%(levelname)s\t%(message)s'
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1898, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/netbox-scanner/logs/netbox-scanner-2021-01-12T16:16:23.599360.log'

[root@HOST netbox-scanner]#

**Comment by FlorianHeigl** [comment]
sounds like it should create a `logs` subdirectory but didn't.
can you try to manually add it?

(fyi, just guessing, i fail to even install it)
